on: push
name: Main
jobs:
  helm-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: helm-check
      uses: igabaydulin/helm-check-action@0.1.4
      env:
        CHART_LOCATION: ./scripts/devtron-reference-helm-charts/cronjob-chart_1-3-0
        CHART_VALUES: ./scripts/devtron-reference-helm-charts/cronjob-chart_1-3-0/app-values.yaml
