name: Lint and Test Charts

on: pull_request

jobs:
  helmlint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Lint helm chart
        run: |
          make helm-dependency-update
          make helm-lint  
