on: pull_request
name: Main
jobs:
  tests:
    runs-on: ubuntu-latest
    outputs:
      charts: ${{ steps.filter.outputs.charts }}
      values: ${{ steps.filter.outputs.values }}
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        list-files: shell
        filters: |
          charts:
            - added|modified: 'scripts/devtron-reference-helm-charts/**'
          values:
            - added|modified: 'scripts/devtron-reference-helm-charts/*/test_values.yaml'
          

    # run only if 'charts' files were changed
  chart-check:
    needs: tests
    if: ${{ needs.tests.outputs.charts == 'true' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: echo ${{ needs.tests.steps.filter.outputs.charts_files }}
    - name: helm-check
      uses: gunish-dt/helm-check-action@0.1.4
      env:
        CHART_LOCATION: ./${{ needs.tests.steps.filter.outputs.charts_files }}
        CHART_VALUES: ./${{ needs.tests.steps.filter.outputs.values_files }}
    
