on: push

name: Helm / Validate

jobs:

  kubeconform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate
        uses: nlamirault/helm-kubeconform-action@v0.1.0
        with:
          charts: ./charts
